# Generated by Django 2.2.9 on 2022-04-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220401_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=30, verbose_name='Текст'),
        ),
    ]
